### ISSUE TITLE
How do you call this in the controller ?

### ISSUE THREAD

**Issue by Mecanik** [ConfidencesApp/zend-geoip#1]
I'm having trouble calling this module in my controller, I cannot access the service either.
I also tried to inject it via the factory, still no success.

Any explanations/help please ?

**Comment by Mecanik** [comment]
I solved it by injecting it in the factory:

```
use Confidences\ZendGeoip\Service\Geoip as GeoipService;
$geopip 	= $container->get(GeoipService::class);
```

**Comment by BnitoBzh** [comment]
Hi ! 
Yes, that's the way it is ;)
